### ISSUE TITLE
Gazebo启动不报错，但是黑屏

### ISSUE THREAD

**Issue by Julius-ZCJ** [huchunxu/ros_exploring#30]
胡老师你好，我正在看ROS机器人开发实践，在运行第6章6.7.2小节中的命令：roslaunch mrobot_gazebo view_mrobot_gazebo.launch时，出现Gazebo启动黑屏，但是没有出现错误。下面介绍我的经历流程：
（1）第一次运行命令：roslaunch mrobot_gazebo view_mrobot_gazebo.launch 出现[REST.cc:205] Error in REST request，通过网上查找，解决了此问题：https://blog.csdn.net/qq_32618327/article/details/104199258
（2）再次运行命令：roslaunch mrobot_gazebo view_mrobot_gazebo.launch ，出现Gazebo黑屏，但是不报错的问题。通过网上查找，可能是因为缺少模型导致的，但是我并不确定是否就是我现在面对的问题：https://blog.csdn.net/chenguangbiao/article/details/120199728
想请教下老师该怎么解决这个问题，如果是缺少模型导致的，我该去哪下载相关模型？

**Comment by huchunxu** [comment]
可以参考这个教程：



***@***.***
 
发件人： Julius.Zhu
发送时间： 2021-09-26 15:34
收件人： huchunxu/ros_exploring
抄送： Subscribed
主题： [huchunxu/ros_exploring] Gazebo启动不报错，但是黑屏 (#30)
胡老师你好，我正在看ROS机器人开发实践，在运行第6章6.7.2小节中的命令：roslaunch mrobot_gazebo view_mrobot_gazebo.launch时，出现Gazebo启动黑屏，但是没有出现错误。下面介绍我的经历流程：
（1）第一次运行命令：roslaunch mrobot_gazebo view_mrobot_gazebo.launch 出现[REST.cc:205] Error in REST request，通过网上查找，解决了此问题：https://blog.csdn.net/qq_32618327/article/details/104199258
（2）再次运行命令：roslaunch mrobot_gazebo view_mrobot_gazebo.launch ，出现Gazebo黑屏，但是不报错的问题。通过网上查找，可能是因为缺少模型导致的，但是我并不确定是否就是我现在面对的问题：https://blog.csdn.net/chenguangbiao/article/details/120199728
想请教下老师该怎么解决这个问题，如果是缺少模型导致的，我该去哪下载相关模型？
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by huchunxu** [comment]
可以参考这个教程：
https://www.guyuehome.com/12269

**Comment by Julius-ZCJ** [comment]
多谢胡老师，我参照教程上的地址，下载模型就可以正常打开了。
